version: "3.8"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    ports:
      - "8080:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
