# Generated by Django 4.1.4 on 2022-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_participants_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='materialName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
