# Generated by Django 4.1.3 on 2023-01-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_coursesenrolled_paymentmethod"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="resolution",),
        migrations.RemoveField(model_name="written", name="length",),
        migrations.AddField(
            model_name="video",
            name="content",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="written",
            name="title",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="privateId",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.private"
            ),
        ),
    ]
