# Generated by Django 4.1.3 on 2023-01-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_video_resolution_remove_written_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetails",
            name="privateId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.private",
            ),
        ),
    ]
