# Generated by Django 4.1.4 on 2023-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_course_link_alter_livechat_chat_enable"),
    ]

    operations = [
        migrations.RemoveField(model_name="teachingunit", name="description",),
        migrations.AddField(
            model_name="teachingunit",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
