# Generated by Django 4.1.3 on 2023-01-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_teachingunit_description_teachingunit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesenrolled",
            name="courseId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.course"
            ),
        ),
    ]
